; GhostWire - ESP32 Wireless Discovery & Device Diagnostics
; Project Configuration for PlatformIO

[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
